apiVersion: skaffold/v1
kind: Config
metadata:
  name: react-app-kubernetes
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  googleCloudBuild:
    projectId: tk-dev-micro
  artifacts:
  - image: asia.gcr.io/tk-dev-micro/my-react-app
    context: frontend
    kaniko:
      cache: {}

deploy:
  kubectl:
    manifests:
    - k8s/my-react-app-deployment.yaml
    - k8s/my-react-app-namespace.yaml
    - k8s/my-react-app-service.yaml

profiles:
- name: oncluster
  build:
    artifacts:
    - image: asia.gcr.io/tk-dev-micro/my-react-app
      context: frontend
      kaniko:
        cache: {}
    googleCloudBuild:
      projectId: tk-dev-micro
#    cluster:
#      namespace: react-dev
