apiVersion: skaffold/v1
kind: Config
metadata:
  name: react-app-kubernetes
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  googleCloudBuild:
    projectId: tk-dev-micro
  artifacts:
  - image: asia.gcr.io/tk-dev-micro/my-react-app
    context: frontend
    kaniko:
      cache: {}

deploy:
  kubectl:
    manifests:
    - k8s/my-react-app-deployment.yaml
    - k8s/my-react-app-namespace.yaml
    - k8s/my-react-app-service.yaml

profiles:
- name: oncluster
  build:
    artifacts:
    - image: asia.gcr.io/tk-dev-micro/my-react-app
      context: frontend
      kaniko:
        cache: {}
        command:
          - /kaniko/executor
          - --insecure-registry
    tagPolicy:
      envTemplate:
        template: '{{.IMAGE_NAME}}:{{.VERSION}}'
    googleCloudBuild:
      projectId: tk-dev-micro
      dockerImage: gcr.io/cloud-builders/docker
      kanikoImage: gcr.io/kaniko-project/executor
      mavenImage: gcr.io/cloud-builders/mvn
      gradleImage: gcr.io/cloud-builders/gradle
