kind: Service
apiVersion: v1
metadata:
  name: my-react-app
  namespace: react-dev
#  annotations:
#    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-react-app
