kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-react-app
  namespace: react-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: asia.gcr.io/tk-dev-micro/my-react-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: kaniko-secret
      restartPolicy: Always
